print("hello world")
print("Hi Centeno!")
print("NICE WAN AM IS NA MABANGIS")
print("Am-is + Centeno = Amino")
print("Expose na ko")
print("Joph")
print("MISS NA KITA CENTEN... -amis")
print("GAWA NA TAYO ICE CANDY ULE")
print("TITE")
print("code ko pa napili.... - Am-is")
